param(
  [int]$PostgresPort = 5432,
  [int]$ApiPort = 8080,
  [int]$FrontendPort = 5173,
  [string]$FrontendHost = "127.0.0.1",
  [string]$FrontendOrigin,
  [switch]$StrictPorts,
  [switch]$RebuildBackend,
  [switch]$FrontendProduction,
  [switch]$NoFrontend,
  [switch]$NoBrowser
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSCommandPath
$frontendDir = Join-Path $projectRoot "frontend"
$envFilePath = Join-Path $projectRoot ".env"
Set-Location -LiteralPath $projectRoot

# Clean up a stray Windows "nul" file that can appear from shell redirection in PowerShell.
$nulPath = Join-Path $projectRoot "nul"
if (Test-Path -LiteralPath $nulPath) {
  Remove-Item -LiteralPath $nulPath -Force -ErrorAction SilentlyContinue
}

function Require-Command {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Command '$Name' was not found in PATH."
  }
}

function New-RandomSecret {
  param([int]$Bytes = 48)

  $buffer = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($buffer)
  } finally {
    if ($rng) {
      $rng.Dispose()
    }
  }
  return [Convert]::ToBase64String($buffer)
}

function New-UrlSafeSecret {
  param([int]$Bytes = 48)

  return (New-RandomSecret -Bytes $Bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Test-PlaceholderValue {
  param([string]$Value)

  if ([string]::IsNullOrWhiteSpace($Value)) {
    return $true
  }

  $normalized = $Value.Trim().ToLowerInvariant()
  if ($normalized.StartsWith("replace-with-")) {
    return $true
  }
  if ($normalized.StartsWith("change-me")) {
    return $true
  }
  if ($normalized -eq "changeme" -or $normalized -eq "your-secret-here" -or $normalized -eq "todo") {
    return $true
  }

  return $false
}

function Read-EnvFile {
  param([string]$Path)

  $values = [ordered]@{}
  if (-not (Test-Path $Path)) {
    return $values
  }

  foreach ($line in Get-Content -LiteralPath $Path) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith("#")) {
      continue
    }

    $parts = $trimmed -split "=", 2
    if ($parts.Count -ne 2) {
      continue
    }

    $key = $parts[0].Trim()
    $value = $parts[1].Trim()
    if ($key) {
      $values[$key] = $value
    }
  }

  return $values
}

function Ensure-ComposeEnvFile {
  param([string]$Path)

  $values = Read-EnvFile -Path $Path
  $updated = $false

  if (-not $values.Contains("POSTGRES_USER") -or (Test-PlaceholderValue -Value $values["POSTGRES_USER"])) {
    $values["POSTGRES_USER"] = "sales"
    $updated = $true
  }
  if (-not $values.Contains("POSTGRES_PASSWORD") -or (Test-PlaceholderValue -Value $values["POSTGRES_PASSWORD"])) {
    $values["POSTGRES_PASSWORD"] = New-UrlSafeSecret -Bytes 24
    $updated = $true
  }
  if (-not $values.Contains("JWT_SECRET") -or (Test-PlaceholderValue -Value $values["JWT_SECRET"])) {
    $values["JWT_SECRET"] = New-UrlSafeSecret -Bytes 64
    $updated = $true
  }
  if (-not $values.Contains("APP_DEMO_ENABLED") -or (Test-PlaceholderValue -Value $values["APP_DEMO_ENABLED"])) {
    $values["APP_DEMO_ENABLED"] = "true"
    $updated = $true
  }

  if ($updated -or -not (Test-Path $Path)) {
    $lines = @(
      "# Local secrets for docker compose. Generated by start-dev.ps1 if missing values."
      "POSTGRES_USER=$($values["POSTGRES_USER"])"
      "POSTGRES_PASSWORD=$($values["POSTGRES_PASSWORD"])"
      "JWT_SECRET=$($values["JWT_SECRET"])"
      "APP_DEMO_ENABLED=$($values["APP_DEMO_ENABLED"])"
    )
    Set-Content -LiteralPath $Path -Value ($lines -join [Environment]::NewLine) -Encoding ascii
    Write-Host "Prepared .env file for docker compose at $Path"
  }

  return $values
}

function Test-DockerReady {
  try {
    docker info *> $null
    return $LASTEXITCODE -eq 0
  } catch {
    return $false
  }
}

function Start-DockerDesktopIfNeeded {
  param([int]$TimeoutSeconds = 180)

  if (Test-DockerReady) {
    Write-Host "Docker daemon is ready."
    return
  }

  Write-Warning "Docker daemon is not ready. Trying to start Docker Desktop..."

  $dockerDesktopPath = $null
  $candidatePaths = @(
    (Join-Path $env:ProgramFiles "Docker\Docker\Docker Desktop.exe"),
    (Join-Path $env:ProgramW6432 "Docker\Docker\Docker Desktop.exe"),
    (Join-Path $env:LocalAppData "Docker\Docker\Docker Desktop.exe")
  ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

  foreach ($candidate in $candidatePaths) {
    if (Test-Path -LiteralPath $candidate) {
      $dockerDesktopPath = $candidate
      break
    }
  }

  if ($dockerDesktopPath) {
    try {
      $existingDesktop = Get-Process -Name "Docker Desktop" -ErrorAction SilentlyContinue
      if (-not $existingDesktop) {
        Start-Process -FilePath $dockerDesktopPath | Out-Null
        Write-Host "Starting Docker Desktop: $dockerDesktopPath"
      } else {
        Write-Host "Docker Desktop process is already running."
      }
    } catch {
      Write-Warning "Failed to start Docker Desktop automatically: $($_.Exception.Message)"
    }
  } else {
    Write-Warning "Docker Desktop executable not found. Start it manually and keep this window open."
  }

  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  while ((Get-Date) -lt $deadline) {
    if (Test-DockerReady) {
      Write-Host "Docker daemon is ready."
      return
    }
    Start-Sleep -Seconds 2
  }

  throw "Docker daemon is not ready after $TimeoutSeconds seconds. Open Docker Desktop, wait for engine startup, and run the script again."
}

function Test-PortAvailable {
  param([int]$Port)

  $inUse = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue
  if ($inUse) {
    return $false
  }

  try {
    $listenerV4 = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
    $listenerV6 = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::IPv6Loopback, $Port)
    $listenerV4.Start()
    $listenerV6.Start()
    $listenerV4.Stop()
    $listenerV6.Stop()
    return $true
  } catch {
    if ($listenerV4) {
      try { $listenerV4.Stop() } catch {}
    }
    if ($listenerV6) {
      try { $listenerV6.Stop() } catch {}
    }
    return $false
  }
}

function Resolve-Port {
  param(
    [int]$RequestedPort,
    [string]$Label
  )

  if (Test-PortAvailable -Port $RequestedPort) {
    return $RequestedPort
  }

  if ($StrictPorts) {
    throw "$Label port $RequestedPort is busy. Use a different port."
  }

  for ($candidate = $RequestedPort + 1; $candidate -le $RequestedPort + 50; $candidate++) {
    if (Test-PortAvailable -Port $candidate) {
      Write-Warning "$Label port $RequestedPort is busy. Using $candidate instead."
      return $candidate
    }
  }

  throw "Could not find a free port for $Label in range $RequestedPort..$($RequestedPort + 50)."
}

function Wait-ForPortListening {
  param(
    [int]$Port,
    [int]$TimeoutSeconds = 60
  )

  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  while ((Get-Date) -lt $deadline) {
    $isListening = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue
    if ($isListening) {
      return $true
    }
    Start-Sleep -Milliseconds 500
  }

  return $false
}

function Wait-ForBackendReady {
  param(
    [int]$Port,
    [int]$TimeoutSeconds = 90
  )

  $url = "http://127.0.0.1:$Port/actuator/health"
  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  while ((Get-Date) -lt $deadline) {
    try {
      $response = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 2
      if ($response -and $response.status -eq "UP") {
        return $true
      }
    } catch {
      # Ignore transient failures until timeout.
    }
    Start-Sleep -Seconds 1
  }

  return $false
}

function Resolve-ComposeBackendPort {
  param(
    [string]$EnvFilePath,
    [int]$FallbackPort
  )

  try {
    $portOutput = & docker compose --env-file $EnvFilePath port backend 8080 2>$null | Select-Object -First 1
    if ([string]::IsNullOrWhiteSpace($portOutput)) {
      return $FallbackPort
    }
    if ($portOutput.Trim() -match ":(\d+)\s*$") {
      return [int]$Matches[1]
    }
  } catch {
    # Keep fallback when compose port cannot be resolved.
  }

  return $FallbackPort
}

function Test-DockerTransientError {
  param([string]$OutputText)

  if ([string]::IsNullOrWhiteSpace($OutputText)) {
    return $false
  }

  $patterns = @(
    "unexpected EOF",
    "TLS handshake timeout",
    "i/o timeout",
    "connection reset by peer",
    "reset by peer",
    "context canceled",
    "temporary failure in name resolution",
    "net/http: request canceled",
    "failed to do request",
    "failed to copy: httpReadSeeker",
    "no route to host",
    "received unexpected HTTP status",
    "failed to solve:.*EOF"
  )

  foreach ($pattern in $patterns) {
    if ($OutputText -match $pattern) {
      return $true
    }
  }

  return $false
}

function Invoke-CommandWithDockerRetry {
  param(
    [string]$CommandLine,
    [string]$FailureMessage,
    [int]$MaxAttempts = 3,
    [switch]$SoftFail
  )

  for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
    $capturedOutput = @()
    cmd /c "$CommandLine 2>&1" | Tee-Object -Variable capturedOutput | Out-Host
    $exitCode = $LASTEXITCODE
    $output = @($capturedOutput)

    if ($exitCode -eq 0) {
      return
    }

    $outputText = ($output -join "`n")
    $isTransient = Test-DockerTransientError -OutputText $outputText
    if (-not $isTransient -or $attempt -eq $MaxAttempts) {
      if ($SoftFail) {
        Write-Warning "$FailureMessage failed with exit code $exitCode. Continuing..."
        return $false
      }
      throw "$FailureMessage failed with exit code $exitCode."
    }

    $delaySeconds = [Math]::Min(30, [Math]::Pow(2, $attempt + 1))
    Write-Warning "Transient Docker error detected. Retry $($attempt + 1)/$MaxAttempts in $delaySeconds sec..."
    Start-Sleep -Seconds $delaySeconds
  }

  return $true
}

function Test-DockerImageLocal {
  param([string]$ImageName)

  if ([string]::IsNullOrWhiteSpace($ImageName)) {
    return $false
  }

  cmd /c "docker image inspect $ImageName >nul 2>&1"
  return $LASTEXITCODE -eq 0
}

function Start-Backend {
  param(
    [int]$PostgresPort,
    [int]$ApiPort,
    [Nullable[int]]$FrontendPort,
    [string]$FrontendHost,
    [string]$FrontendOrigin,
    [string]$EnvFilePath
  )

  $prevPostgresPort = $env:POSTGRES_PORT
  $prevApiPort = $env:API_PORT
  $prevCorsAllowedOrigins = $env:APP_CORS_ALLOWED_ORIGINS

  try {
    $env:POSTGRES_PORT = "$PostgresPort"
    $env:API_PORT = "$ApiPort"
    if ($null -ne $FrontendPort) {
      $origins = @(
        "http://127.0.0.1:$FrontendPort",
        "http://localhost:$FrontendPort"
      )
      if (-not [string]::IsNullOrWhiteSpace($FrontendOrigin)) {
        $origins += $FrontendOrigin.Trim()
      } elseif (-not [string]::IsNullOrWhiteSpace($FrontendHost) `
          -and $FrontendHost -ne "127.0.0.1" `
          -and $FrontendHost -ne "localhost" `
          -and $FrontendHost -ne "0.0.0.0" `
          -and $FrontendHost -ne "::") {
        $origins += "http://${FrontendHost}:$FrontendPort"
      }
      $env:APP_CORS_ALLOWED_ORIGINS = ($origins | Select-Object -Unique) -join ","
    } else {
      $env:APP_CORS_ALLOWED_ORIGINS = @(
        "http://127.0.0.1:5173",
        "http://localhost:5173",
        "http://127.0.0.1:4173",
        "http://localhost:4173"
      ) -join ","
    }

    if ($RebuildBackend) {
      Write-Host "Rebuilding backend image without cache..."
      Invoke-CommandWithDockerRetry `
        -CommandLine "docker compose --env-file ""$EnvFilePath"" build --no-cache backend" `
        -FailureMessage "docker compose build --no-cache backend"
    }

    $requiredBaseImages = @(
      "maven:3.9-eclipse-temurin-21",
      "eclipse-temurin:21-jre"
    )
    foreach ($image in $requiredBaseImages) {
      if (Test-DockerImageLocal -ImageName $image) {
        continue
      }
      Write-Host "Pulling missing backend base image '$image' (with retry on transient network errors)..."
      Invoke-CommandWithDockerRetry `
        -CommandLine "docker pull $image" `
        -FailureMessage "docker pull $image" `
        -MaxAttempts 5 `
        -SoftFail
    }

    Write-Host "Starting backend and database with docker compose (without forced rebuild)..."
    Invoke-CommandWithDockerRetry `
      -CommandLine "docker compose --env-file ""$EnvFilePath"" up -d" `
      -FailureMessage "docker compose up -d" `
      -MaxAttempts 5

    $actualApiPort = Resolve-ComposeBackendPort -EnvFilePath $EnvFilePath -FallbackPort $ApiPort
    if ($actualApiPort -ne $ApiPort) {
      Write-Warning "Backend is published on port $actualApiPort (requested $ApiPort). Frontend proxy will use $actualApiPort."
    }
    return $actualApiPort
  } finally {
    if ($null -eq $prevPostgresPort) {
      Remove-Item Env:POSTGRES_PORT -ErrorAction SilentlyContinue
    } else {
      $env:POSTGRES_PORT = $prevPostgresPort
    }

    if ($null -eq $prevApiPort) {
      Remove-Item Env:API_PORT -ErrorAction SilentlyContinue
    } else {
      $env:API_PORT = $prevApiPort
    }

    if ($null -eq $prevCorsAllowedOrigins) {
      Remove-Item Env:APP_CORS_ALLOWED_ORIGINS -ErrorAction SilentlyContinue
    } else {
      $env:APP_CORS_ALLOWED_ORIGINS = $prevCorsAllowedOrigins
    }
  }
}

function Start-Frontend {
  param(
    [int]$ApiPort,
    [int]$FrontendPort,
    [string]$FrontendHost,
    [switch]$Production
  )

  if (-not (Test-Path $frontendDir)) {
    throw "Frontend directory not found: $frontendDir"
  }

  Require-Command "npm"
  Require-Command "npx"

  $envLocalPath = Join-Path $frontendDir ".env.local"
  $apiBase = if ($Production) { "http://127.0.0.1:$ApiPort/api" } else { "/api" }
  $envLocalContent = @(
    "VITE_API_BASE=$apiBase",
    "VITE_PROXY_API_HOST=127.0.0.1",
    "VITE_PROXY_API_PORT=$ApiPort"
  ) -join [Environment]::NewLine
  Set-Content -Path $envLocalPath -Value $envLocalContent -Encoding ascii

  if (-not (Test-Path (Join-Path $frontendDir "node_modules"))) {
    Write-Host "Installing frontend dependencies..."
    Push-Location $frontendDir
    try {
      npm install
      if ($LASTEXITCODE -ne 0) {
        throw "npm install failed with exit code $LASTEXITCODE."
      }
    } finally {
      Pop-Location
    }
  }

  $escapedFrontendDir = $frontendDir.Replace("'", "''")
  if ($Production) {
    $frontendCommand = @(
      "`$ErrorActionPreference = 'Stop'"
      "Set-Location -LiteralPath '$escapedFrontendDir'"
      "npm run build"
      "if (`$LASTEXITCODE -ne 0) { throw 'npm run build failed with exit code ' + `$LASTEXITCODE }"
      "npx vite preview --host $FrontendHost --port $FrontendPort --strictPort"
    ) -join "; "
    Write-Host "Starting frontend in production mode (build + preview) in a new PowerShell window..."
  } else {
    $frontendCommand = @(
      "`$ErrorActionPreference = 'Stop'"
      "Set-Location -LiteralPath '$escapedFrontendDir'"
      "npx vite --host $FrontendHost --port $FrontendPort --strictPort"
    ) -join "; "
    Write-Host "Starting frontend in development mode in a new PowerShell window..."
  }

  Start-Process powershell -ArgumentList "-NoExit", "-Command", $frontendCommand | Out-Null
}

function Stop-ProjectViteProcesses {
  $escapedFrontendDir = [Regex]::Escape($frontendDir)
  $viteProcesses = Get-CimInstance Win32_Process -Filter "Name = 'node.exe'" |
    Where-Object {
      $_.CommandLine -and
      $_.CommandLine -match "vite\.js" -and
      $_.CommandLine -match $escapedFrontendDir
    }

  foreach ($proc in $viteProcesses) {
    Write-Host "Stopping existing frontend process PID $($proc.ProcessId)..."
    Stop-Process -Id $proc.ProcessId -Force -ErrorAction SilentlyContinue
  }
}

Require-Command "docker"
Start-DockerDesktopIfNeeded
$composeEnv = Ensure-ComposeEnvFile -Path $envFilePath

$effectivePostgresPort = Resolve-Port -RequestedPort $PostgresPort -Label "PostgreSQL"
$effectiveApiPort = Resolve-Port -RequestedPort $ApiPort -Label "API"

if (-not $NoFrontend) {
  Stop-ProjectViteProcesses
}

$effectiveFrontendPort = $null
if (-not $NoFrontend) {
  $effectiveFrontendPort = Resolve-Port -RequestedPort $FrontendPort -Label "Frontend"
}

$effectiveFrontendHost = $FrontendHost

$effectiveApiPort = Start-Backend `
  -PostgresPort $effectivePostgresPort `
  -ApiPort $effectiveApiPort `
  -FrontendPort $effectiveFrontendPort `
  -FrontendHost $effectiveFrontendHost `
  -FrontendOrigin $FrontendOrigin `
  -EnvFilePath $envFilePath

$backendReady = Wait-ForBackendReady -Port $effectiveApiPort -TimeoutSeconds 90
if (-not $backendReady) {
  Write-Warning "Backend health check did not report UP within 90 seconds. Frontend may show temporary API errors."
}

if (-not $NoFrontend) {
  Start-Frontend `
    -ApiPort $effectiveApiPort `
    -FrontendPort $effectiveFrontendPort `
    -FrontendHost $effectiveFrontendHost `
    -Production:$FrontendProduction

  if (-not (Wait-ForPortListening -Port $effectiveFrontendPort -TimeoutSeconds 60)) {
    Write-Warning "Frontend did not start listening on port $effectiveFrontendPort within 60 seconds."
  }
}

$frontendDisplayHost = $effectiveFrontendHost
if ([string]::IsNullOrWhiteSpace($frontendDisplayHost) -or $frontendDisplayHost -eq "0.0.0.0" -or $frontendDisplayHost -eq "::") {
  $frontendDisplayHost = "127.0.0.1"
}

if (-not $NoBrowser) {
  if ((-not $NoFrontend) -and (Wait-ForPortListening -Port $effectiveFrontendPort -TimeoutSeconds 2)) {
    Start-Process "http://${frontendDisplayHost}:$effectiveFrontendPort" | Out-Null
  } else {
    Write-Warning "Browser was not opened automatically because frontend is disabled or not reachable yet."
  }
}

Write-Host "Done."
Write-Host "Backend API: http://127.0.0.1:$effectiveApiPort/api"
if (-not $NoFrontend) {
  Write-Host "Frontend: http://${frontendDisplayHost}:$effectiveFrontendPort"
  if ($FrontendProduction) {
    Write-Host "Frontend mode: production (vite preview, React production build)"
  } else {
    Write-Host "Frontend mode: development (vite dev)"
  }
}
if ($composeEnv["APP_DEMO_ENABLED"] -eq "true") {
  Write-Host "Demo users: berezka / kvartal / yantar / manager / logistician / driver1 / driver2 / driver3"
  Write-Host "Demo passwords are unique per user and stored as bcrypt hashes in DB."
}
